export const constants = {
    FETCH_WEATHER_DATA : "FETCH_WEATHER_DATA",
    FETCH_WEATHER_DATA_SUCCESS : "FETCH_WEATHER_DATA_SUCCESS",
    FETCH_WEATHER_DATA_FAILED : "FETCH_WEATHER_DATA_FAILED",
}



